// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOCQFfW6zQxIABjt5ApC5mPu0nyC0Th3k',
    appId: '1:605491078088:web:209271a8dbe1d7a68816fd',
    messagingSenderId: '605491078088',
    projectId: 'coral-missao-4a90d',
    authDomain: 'coral-missao-4a90d.firebaseapp.com',
    storageBucket: 'coral-missao-4a90d.firebasestorage.app',
    measurementId: 'G-E0PBKDYH5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnrCIS-sCSLw5IMJ_mz5enlkF-Ccx4G2o',
    appId: '1:605491078088:android:d3e2e7e2b7ea47758816fd',
    messagingSenderId: '605491078088',
    projectId: 'coral-missao-4a90d',
    storageBucket: 'coral-missao-4a90d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhkx4854xQ2HhUQGLi3tJ87uXrGwgbiQI',
    appId: '1:605491078088:ios:e7613834113434568816fd',
    messagingSenderId: '605491078088',
    projectId: 'coral-missao-4a90d',
    storageBucket: 'coral-missao-4a90d.firebasestorage.app',
    iosBundleId: 'com.example.coralMissao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhkx4854xQ2HhUQGLi3tJ87uXrGwgbiQI',
    appId: '1:605491078088:ios:e7613834113434568816fd',
    messagingSenderId: '605491078088',
    projectId: 'coral-missao-4a90d',
    storageBucket: 'coral-missao-4a90d.firebasestorage.app',
    iosBundleId: 'com.example.coralMissao',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOCQFfW6zQxIABjt5ApC5mPu0nyC0Th3k',
    appId: '1:605491078088:web:8f0c61727b2c69798816fd',
    messagingSenderId: '605491078088',
    projectId: 'coral-missao-4a90d',
    authDomain: 'coral-missao-4a90d.firebaseapp.com',
    storageBucket: 'coral-missao-4a90d.firebasestorage.app',
    measurementId: 'G-5SLC7HPNSP',
  );
}
